classes: &classes
    - class_1
seed: &seed 1 
model:
    model_name: &model_name "distilroberta-base"
    classes: *classes
batch_size: 768
loader:
    num_workers: 40
data:
    classes: *classes
    model_name: *model_name
    max_length: 128
instance:
    val_split: 0.15
    seed: *seed
trainer:
    gpus: 4
    distributed_backend: ddp
    use_amp: True
    max_epochs: 100
    num_sanity_val_steps: 5
early_stopping:
    monitor: val_loss
    patience: 10
    mode: min
loss:
    type: CrossEntropyLoss
    kwargs: {}
optim:
    type: Adam
    kwargs:
        lr: 3.0e-05
optim_scheduler:
    type: ExponentialLR
    kwargs:
        gamma: 0.99
