classes: &classes
    - null
data:
    classes: *classes
instance:
    val_split: 0.3
model:
    type: null
    classes: *classes
trainer:
    gpus: 1
    distributed_backend: None
    use_amp: False
    max_epochs: 100
    num_sanity_val_steps: 5
early_stopping:
    monitor: val_loss
    patience: 10
    mode: min
loss:
    type: BCEWithLogitsLoss
    kwargs:
        pos_weight: [1.]
optim:
    type: Adam
    kwargs:
        lr: 5.0e-06
optim_scheduler:
    type: ExponentialLR
    kwargs:
        gamma: 0.99